### ISSUE TITLE
I think Stories fully broke + another bug with the wall

### ISSUE THREAD

**Issue by notNSANE** [kurtextrem/Layoutify-for-Instagram#109]
Not sure if it's just me, but opening a story opens in some kind of background and the front is still the normal instagram wall.

Also, a bug with the wall, I'm seeing like 10 "stuck" posts where you cannot see videos or save them, you need to scroll down to see the posts again to save stuff.

**Comment by kurtextrem** [comment]
Hi, thank you, I see the story bug.

Could you explain to me what you mean by wall?

**Comment by kurtextrem** [comment]
Fix for the story issue is on the way, the issue was much bigger (e.g. any navigation broke)

**Comment by notNSANE** [comment]
The wall is the main feed/front page.

**Comment by GitGuuuud** [comment]
When u clicked post contain multiple pictures, "dot indicator" on the bottom is gone on the pop up viewer.

**Comment by kurtextrem** [comment]
@GitGuuuud Can you share a screenshot please?

**Comment by GitTheGreek** [comment]
My Problem solved by changed modal width back to 85 from 50.
[50](https://imgur.com/KFinDHe)
[85](https://imgur.com/G5qEBeB)

**Comment by GitGuuuud** [comment]
@kurtextrem 
My Problem solved by changed modal width back to 85 from 50.
[50](https://imgur.com/KFinDHe)
[85](https://imgur.com/G5qEBeB)

**Comment by kurtextrem** [comment]
The version that fixes the original issue is in review since the 9th of December.... Can't do anything about it, can't even publish a new version :(

**Comment by GitGuuuud** [comment]
Main page broke and unable to load. Stories top section is gone (loading bar/pages, profile icon & name).

**Comment by kurtextrem** [comment]
Still working for me, do you see any error in the Dev Tools? Or on the page?

**Comment by GitGuuuud** [comment]
Only happen to latest brave browser

>Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at main.js:352:41
main.js:2 ReferenceError: Cannot access 'fullSizeCondition' before initialization
    at Object.fullPhoto [as IMG] (main.js:384:2)
    at handleNode (main.js:221:66)
logAndReject @ main.js:2
main.js:384 Uncaught (in promise) ReferenceError: Cannot access 'fullSizeCondition' before initialization
    at Object.fullPhoto [as IMG] (main.js:384:2)
    at handleNode (main.js:221:66)
commons.bundle.js:296 Uncaught TypeError: Cannot read properties of null (reading '__k')
    at x (commons.bundle.js:296:61)
    at P (feed.bundle.js:55:29)
    at Object.758 (feed.bundle.js:57:121)
    at e (runtime.bundle.js:5:13)
    at feed.bundle.js:59:30
    at Function.e.O (runtime.bundle.js:8:23)
    at o (runtime.bundle.js:17:10)
    at commons.bundle.js:1:55
(index):55 Uncaught TypeError: Cannot read properties of undefined (reading 'push')
    at window.onerror ((index):55:29)
main.js:2 ReferenceError: Cannot access 'fullSizeCondition' before initialization
    at Object.fullPhoto [as IMG] (main.js:384:2)
    at handleNode (main.js:221:66)
logAndReject @ main.js:2
main.js:384 Uncaught (in promise) ReferenceError: Cannot access 'fullSizeCondition' before initialization
    at Object.fullPhoto [as IMG] (main.js:384:2)
    at handleNode (main.js:221:66)
main.js:2 ReferenceError: Cannot access 'fullSizeCondition' before initialization
    at Object.fullPhoto [as IMG] (main.js:384:2)
    at handleNode (main.js:221:66)
logAndReject @ main.js:2
main.js:384 Uncaught (in promise) ReferenceError: Cannot access 'fullSizeCondition' before initialization
    at Object.fullPhoto [as IMG] (main.js:384:2)
    at handleNode (main.js:221:66)
main.js:2 ReferenceError: Cannot access 'fullSizeCondition' before initialization
    at Object.fullPhoto [as IMG] (main.js:384:2)
    at handleNode (main.js:221:66)
logAndReject @ main.js:2
main.js:384 Uncaught (in promise) ReferenceError: Cannot access 'fullSizeCondition' before initialization
    at Object.fullPhoto [as IMG] (main.js:384:2)
    at handleNode (main.js:221:66)
8main.js:2 ReferenceError: Cannot access 'fullSizeCondition' before initialization
    at fullPhoto (main.js:384:2)
    at NodeList.forEach (<anonymous>)
    at Object.DIV (main.js:158:32)
    at Object.ARTICLE (main.js:153:17)
    at handleNode (main.js:221:66)
logAndReject @ main.js:2
8main.js:384 Uncaught (in promise) ReferenceError: Cannot access 'fullSizeCondition' before initialization
    at fullPhoto (main.js:384:2)
    at NodeList.forEach (<anonymous>)
    at Object.DIV (main.js:158:32)
    at Object.ARTICLE (main.js:153:17)
    at handleNode (main.js:221:66)
main.js:2 ReferenceError: Cannot access 'fullSizeCondition' before initialization
    at Object.fullPhoto [as IMG] (main.js:384:2)
    at handleNode (main.js:221:66)
logAndReject @ main.js:2
main.js:384 Uncaught (in promise) ReferenceError: Cannot access 'fullSizeCondition' before initialization
    at Object.fullPhoto [as IMG] (main.js:384:2)
    at handleNode (main.js:221:66)
5main.js:2 ReferenceError: Cannot access 'fullSizeCondition' before initialization
    at fullPhoto (main.js:384:2)
    at NodeList.forEach (<anonymous>)
    at Object.DIV (main.js:158:32)
    at handleNode (main.js:221:66)
logAndReject @ main.js:2
5main.js:384 Uncaught (in promise) ReferenceError: Cannot access 'fullSizeCondition' before initialization
    at fullPhoto (main.js:384:2)
    at NodeList.forEach (<anonymous>)
    at Object.DIV (main.js:158:32)
    at handleNode (main.js:221:66)

**Comment by kurtextrem** [comment]
Thank you, that helps fixing it.

**Comment by kurtextrem** [comment]
3.11.1 will fix it https://github.com/kurtextrem/Layoutify-for-Instagram/commit/ddd71f5fc7df8bd931081e46f1c8b92ef9c394c0
